version: '3'

services:
  todo-backend:
    container_name: todo
    build: ./
    working_dir: /usr/src/todo
    networks:
      - default
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/todo

  db:
      image: mysql:latest
      restart: always
      environment:
        MYSQL_DATABASE: 'todo'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - '3306:3306'
      expose:
        - '3306'
      volumes:
        - my-db:/var/lib/mysql

networks:
  default:

volumes:
  my-db: